### PR TITLE
Fix workflow input value in wp3 process

### PR DESCRIPTION
**Pull request by MatProv**
Related to #191 

- Add ``data`` as a ``workflow_input_value`` data type.
- Fix stdout/stderr log file not present in workflow.

### CODE REVIEW

**Comment by MatProv** [comment]
@fmigneault Things might silently break following this change. I need your review on this please.
Type mismatch not present anymore, but can't be fully tested locally with `test_workflow_subset_picker` since `wpsoutputs` in local are not accessible, so getting a 404 in `utils.fetch_file()`

**Comment by fmigneault** [comment]
We should add a test to avoid unexpected errors + detect them in the future.

**Comment by MatProv** [comment]
> We should add a test to avoid unexpected errors + detect them in the future.

I suggest making sure the functional test `test_workflow_subset_picker` gets executed by the CI would do the trick.

**Comment by fmigneault** [comment]
> I suggest making sure the functional test test_workflow_subset_picker gets executed by the CI would do the trick.
This test is currently not ran on Travis.
Running this test makes sure that href as well as data attributes are parsed, since the subset use LiteralData for lat/lon.

I'm a bit confused by what you are running. Looking at the definition of `test_workflow_subset_picker`, the workflow refers to a single process `ColibriFlyingpigeon_SubsetBbox` which is WPS-1 reference. Therefore, the portion of code modified in this PR (WPS-3) should not even be called. It is the class in `weaver/processes/wps1_process.py` that should be executed.

**Comment by MatProv** [comment]
> I'm a bit confused by what you are running. Looking at the definition of `test_workflow_subset_picker`, the workflow refers to a single process `ColibriFlyingpigeon_SubsetBbox` which is WPS-1 reference. Therefore, the portion of code modified in this PR (WPS-3) should not even be called. It is the class in `weaver/processes/wps1_process.py` that should be executed.

Yes, that's a weird behaviour. I actually have no clue why `wp3_process` is getting called instead of `wps1_process`.
Since this PR fixes (well, I guess) the `TypeMismatch`, that means that another misbehaviour might occur beforehand in the process, at the time of selecting which `wpsX_process` version to use.

**Comment by fmigneault** [comment]
> Yes, that's a weird behaviour. I actually have no clue why `wp3_process` is getting called instead of `wps1_process`.
> Since this PR fixes (well, I guess) the `TypeMismatch`, that means that another misbehaviour might occur beforehand in the process, at the time of selecting which `wpsX_process` version to use.

If this is an actual issue, it could be investigated using another PR/test case. 
Regardless of that, I would like to have more "targeted" tests that verify the feature/fix added here. 
I don't like the idea of considering the fix as tested through a huge workflow which imply a lot of other functionalities (and other potential cause of error).

Basically, we need clear and simple test that runs `Wps3Process.execute` (as if CWL was calling it to run a job), and verify that inputs of different types are parsed as expected. Using a mock of `WpsProcessInterface.make_request`, we can simulate the responses of each step without actually calling a real server.

**Comment by MatProv** [comment]
> If this is an actual issue, it could be investigated using another PR/test case.
> Regardless of that, I would like to have more "targeted" tests that verify the feature/fix added here.
> I don't like the idea of considering the fix as tested through a huge workflow which imply a lot of other functionalities (and other potential cause of error).
> 
> Basically, we need clear and simple test that runs `Wps3Process.execute` (as if CWL was calling it to run a job), and verify that inputs of different types are parsed as expected. Using a mock of `WpsProcessInterface.make_request`, we can simulate the responses of each step without actually calling a real server.

#195 will get rid of that misbehaviour related to WPS1-WPS3.
And yes, a targeted test will be added in order to validate input parsing.

**Review by fmigneault — APPROVED** [review]
Added missing test + some small patch for new change by AWS S3

**Pull request merged**
