### PR TITLE
handle WPS status location path

### PR DESCRIPTION
**Pull request by fmigneault**

### CODE REVIEW

**Comment by fmigneault** [comment]
@MatProv 
tests are passing with this change
if you can run your branch with status-location handling in this case, we can consider as a valid candidate

**Comment by MatProv** [comment]
@fmigneault do you mean merging `status-location` in `esgf-cwt-process-rebase` ?

**Comment by fmigneault** [comment]
> 
> 
> do you mean merging `status-location` in `esgf-cwt-process-rebase` ?

@MatProv 
Yes, to try that your use cases with workflow and other type of processes still work.

**Comment by MatProv** [comment]
@fmigneault test passed on `esgf-cwt-process-rebase` after merging (without committing, will rebuild on master)
I consider this branch as working

**Pull request merged**
