### PR TITLE
Updated README before distribution

### PR DESCRIPTION
**Pull request by tomLandry**
Review wording, adding links

### CODE REVIEW

**Comment by fmigneault** [comment]
@tomLandry @dbyrns 
somehow wasn't merged?

**Comment by tomLandry** [comment]
No, it looks fine to me looking at it again. It was not a big change. A few links at the bottom, revised langage.

**Comment by dbyrns** [comment]
For me it looks good : https://raw.githubusercontent.com/crim-ca/weaver/master/README.rst

**Comment by fmigneault** [comment]
I'm talking about this change
https://github.com/crim-ca/weaver/pull/27/commits/ce4ccb8f52d66336f7fde06139f9680b3d854e60

**Comment by dbyrns** [comment]
You're right, great catch @fmigneault !

**Comment by dbyrns** [comment]
But @tomLandry commit directly in master wiping its own modifications : https://github.com/crim-ca/weaver/commit/587098350f0536965fc85d2042dfce5477616c86

**Comment by tomLandry** [comment]
Yep, I really did that. So point is that the README is satisfactory to me right now. Thanks for the vigilance boys!

**Pull request merged**
